config/routes.rb
Rails.application.routes.draw do
  root "photos#index"
  resources :photos
  resources :static_pages, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    def set_flickr
        FlickRaw.api_key = ENV["API_KEY"]
        FlickRaw.shared_secret= ENV["SHARED_SECRET"]
        flickr.access_token = ENV["ACCESS_TOKEN"]
        flickr.access_secret = ENV["ACCESS_SECRET"]
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    require "flickraw"
    before_action :set_flickr, only: [:create, :destroy, :index]
    def index
        @photos = Photo.all
    end
    def show
       @photo = Photo.find(params[:id]) 
    end
    def new
        @photo = Photo.new
    end
    def create
        photo_id = flickr.upload_photo params[:photo].tempfile.path, :title => params[:title], :description => params[:desc]
        photo_url = FlickRaw.url_o(flickr.photos.getInfo(photo_id: photo_id))
        @photo = Photo.new
        @photo.photo_id = photo_id
        @photo.photo_url = photo_url
        @photo.title = params[:title]
        @photo.desc = params[:desc]
        respond_to do |format|
            if @photo.save
                format.html { redirect_to @photo }
                format.json { render :show, status: :created, location: @photo }
            else
                format.html { render action: ‘new’ }
                format.json { render json: @photo.errors, status: :unprocessable_entity }
            end
    end
    def destroy
        flickr.photos.delete(photo_id: @photo.photo_id)
        @photo.destroy
        respond_to do |format|
        format.html { redirect_to photos_url }
        format.json { head :no_content }
        end
    end




    end
    private
    def photo_params
       params.require(:photo).permit(:title, :desc) 
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    require "flickraw"
    before_action :set_flickr
    def index
        if params[:flickr_id]
          @flickr = params[:flickr_id]
        else
          @flickr = nil
        end
    end
end

        #if params[:flickr_id]
        #  @photos = flickr.photos.search(user_id: params[:flickr_id])
    #    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<%= link_to("Add a new photo", new_photo_path) %>
<% @photos.each do |photo| %>
    <%= image_tag(photo.id) %>
<% end %>

app/views/photos/new.html.erb
<%= form_for(@photo, html: {:multipart => true}) do |f| %>
<%= f.text_field :title %>
<%= f.text_field :desc %>
<%= file_field_tag :photo %>
<%= f.submit %>
<% end %>

app/views/photos/show.html.erb
<%= image_tag(@photo.photo_url ) %>
<%= @photo.title %>
<%= @photo.desc %>

app/views/static_pages/index.html.erb
<%= form_tag static_pages_path, method: :get do %>
  <%= text_field_tag :flickr_id %>
  <%= submit_tag "Search" %>
<% end %>


<% if @flickr %>
        <p>Flickr id is <%= @flickr %></p>
        <% photos = flickr.photos.search(user_id: params[:flickr_id]) %>
        <% photos.each do |photo| %>
            <%= image_tag "https://farm#{photo.farm}.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}.jpg" %>
        <% end %>
<% end %>